name: 'Yarn Package Publish'
description: 'Detect if the version defined in the package.json is unpublished, and if so, publishes it. It will also push a git tag onto the current commit.'
author: 'luvies'
inputs:
  package-path:
    description: 'The path to the root directory containing the package.json.'
  dry-run:
    description: 'If set to true, all actions that would have been performed are skipped.'
    default: 'false'
  skipped-versions:
    description: 'A semver string of the versions to skip publishing of (see https://npm.im/semver for syntax).'
  skip-git-tag:
    description: 'If set to true, then this action will not also write a git tag on the published commit.'
    default: 'false'
runs:
  using: 'node12'
  main: 'build/action.js'
